---
title: "Final Project"
author: Junhui Mi (jm4998)
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%")

library(arsenal)
library(dplyr)
library(tidyverse)
library(ggridges)
library(HH)
library(leaps)
library(corrplot)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


```{r, results = 'asis'}
law = read_csv("./data/Lawsuit.csv") %>%
  mutate(Sal = (Sal94 + Sal95)/2) %>%
  dplyr::select(-ID, -Sal94, -Sal95)

law$Dept <- ifelse(law$Dept == 6, 0, ifelse(law$Dept != 6, law$Dept, NA))
law$Rank <- ifelse(law$Rank == 3, 0, ifelse(law$Rank != 3, law$Rank, NA))

law_1 = law %>%
  mutate(
    Gender = as.factor(Gender),
    Dept = as.factor(Dept),
    Clin = as.factor(Clin),
    Cert = as.factor(Cert),
    Rank = as.factor(Rank)
  )

law_df = law %>%
  mutate(Gender = factor(Gender, levels = c(0,1), labels = c("Female", "Male")),
         Dept = factor(Dept, levels = c(0,1,2,3,4,5), 
                       labels = c("Surgery", "Biochemistry/Molecular Biology", "Physiology", "Genetics", "Pediatrics", "Medicine")),
         Clin = factor(Clin, levels = c(0,1), labels = c("Primarily research emphasis", "Primarily clinical emphasis")),
         Cert = factor(Cert, levels = c(0,1), labels = c("not certified", "Board certified")),
         Rank = factor(Rank, levels = c(0,1,2), labels = c("Full professor", "Assistant", "Associate")))

my_labels <- list(Dept = "Department", Gender = "Gender", Clin = "Research/Clinical emphasis", Cert = "Not/Board Certificated", Prate = "Publication rate", Exper = "Experience(years)", Rank = "Title", Sal = "Average Salary in 1994-1995")

my_controls <- tableby.control(
  total = T,
  test = F, 
  digits = 2,
  numeric.stats = c("meansd", "medianq1q3", "range"),
  cat.stats = c("countpct"),
  stats.labels = list(
    meansd = "Mean (SD)",
    medianq1q3 = "Median (Q1, Q3)",
    range = "Min - Max",
    countpct = "N (%)"))

tab1 <- tableby(Gender ~ Dept + Clin + Cert + Prate + Exper + Rank + Sal, data = law_df, control = my_controls)

summary(tab1, title = "Summary by Gender", 
        labelTranslations = my_labels, text = T)
```

```{r}
attach(law)
pairs(law)
cor_mat = round(cor(law),2)


par(mar = c(4,5,1,1))
cor(law_df[ ,c(5,6,8)]) %>% 
  corrplot(method = "circle", type = "upper", diag = FALSE)

sal_log = log(law$Sal)

par(mfrow = c(1,2))

hist(law$Sal, xlab = "Salary", freq = T, col = 2)

hist(sal_log, xlab = "lm(Salary)", freq = T, col = 2)

```

```{r}
law_trans = law_df %>%
  mutate(
    sal_log = log(law$Sal)
  ) %>% 
  dplyr::select(-Sal)


mult_fit = lm(sal_log ~ Dept + Gender + Clin + Cert + Prate + Rank + Exper, data = law_trans)
step(mult_fit, direction = 'backward')
mult_fit = lm(sal_log ~ Dept + Clin + Cert + Prate + Rank + Exper, data = law_trans)
summary(mult_fit)
```

```{r}
# divide the df for strata analysis

male_sal = law_trans %>% 
  janitor::clean_names() %>% 
  filter(gender == "Male")

male_model = lm(sal_log ~ dept + clin + cert + prate + rank + exper, data = male_sal)

summary(male_model)

female_sal = law_trans %>% 
  janitor::clean_names() %>% 
  filter(gender == "Female")

female_model = lm(sal_log ~ dept + clin + cert + prate + rank + exper, data = female_sal)

summary(female_model)
```

```{r}
a = law_trans %>% 
  janitor::clean_names() %>% 
  group_by(gender) %>% 
  summarise(mean_sal_log = mean(sal_log), 
            sd_sal_log = sd(sal_log))

ggplot(data = a, aes(x = gender, y = mean_sal_log, fill = gender)) + 
  geom_bar(stat = "identity", width = .5, position = "dodge") + 
  geom_errorbar(aes(ymin = mean_sal_log - sd_sal_log, ymax = mean_sal_log + sd_sal_log), position = position_dodge(width = 0.5), width = .3)

# direct way
# law_trans %>% group_by(Gender) %>% summarise(mean_sal = mean(sal_log))
# law %>% group_by(Gender) %>% summarise(mean_sal = mean(Sal))
```

