---
title: "bm project_update 12/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
law_df = read_csv("./data/Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(mean_sal = (sal94 + sal95)/2) %>% 
  mutate(
    gender = as.factor(gender),
    dept = as.factor(dept),
    clin = as.factor(clin),
    cert = as.factor(cert),
    rank = as.factor(rank)
  ) %>% 
  mutate(gender = factor(gender, levels = c(0,1), labels = c("Female", "Male")),
         dept = factor(dept, levels = c(6,1,2,3,4,5), 
                       labels = c("Surgery", "Biochemistry/Molecular Biology", "Physiology", "Genetics", "Pediatrics", "Medicine")),
         clin = factor(clin, levels = c(0,1), labels = c("Primarily research emphasis", "Primarily clinical emphasis")),
         cert = factor(cert, levels = c(0,1), labels = c("not certified", "Board certified")),
         rank = factor(rank, levels = c(3,1,2), labels = c("Full professor", "Assistant", "Associate")))

```

first, fit only gender in the model
```{r}
model_1 = lm(mean_sal~gender, data = law_df)
```

see if a variable is a confounder (lec 15, page 29; epi lec 7, page 69)

```{r confounders}
# dept
model_dept = lm(mean_sal~gender + dept, data = law_df)

model_1 %>% broom::tidy()

model_dept %>% broom::tidy()

# yes

# rank 

model_rank = lm(mean_sal~gender + rank, data = law_df)

model_rank %>% broom::tidy()

# not a confounder

# prate

model_prate = lm(mean_sal~gender + prate, data = law_df)

model_prate %>% broom::tidy()

# maybe? should I use anova or something else to determine if it's a confounder? 
```

There is a big diffenrence in magnitude of model coefficients, therefore we will partition the data by `dept`. 

```{r partition data by dept}
# law_df %>% group_by(dept) %>% summarise(n = n())

surg_df = law_df %>% filter(dept == "Surgery")
bio_df = law_df %>% filter(dept == "Biochemistry/Molecular Biology")
phys_df = law_df %>% filter(dept == "Physiology")
gene_df = law_df %>% filter(dept == "Genetics")
pedia_df = law_df %>% filter(dept == "Pediatrics")
med_df = law_df %>% filter(dept == "Medicine")
```

fit models with partitioned data (in surgery department)

```{r surg dept}
# surgery department
surg_model = lm(mean_sal~gender, data = surg_df)

anova(surg_model)

surg_model %>% broom::tidy()

# p-value 0.2 ?????????????????????????????????????????????????????????????

summary(surg_model)
```

biochem department

```{r}
bio_model = lm(mean_sal~gender, data = bio_df)

bio_model %>% broom::tidy()

bio_model %>% summary()

# p-value = 0.0375
```

physiology department

```{r}
phys_model = lm(mean_sal~gender, data = phys_df)

phys_model %>% broom::tidy()

phys_model %>% summary()

# p-value = 0.00462
```

